<?php

namespace Tests\Feature;

use App\Comment;
use App\Post;
use Illuminate\Support\Facades\Artisan;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class CommentsApiTest extends TestCase
{
    /**
     * Configure environnement Test
     */
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        //initialisation bdd
        Artisan::call('migrate');
    }


    public function testGetComments(){
        //Create article
        $post = factory(Post::class)->create();

        //Create Comment
        $comment = factory(Comment::class)->create(['commentable_type' => 'Post', 'commentable_id' => $post->id]);
        $comment2 = factory(Comment::class)->create(['commentable_type' => 'Post', 'commentable_id' => $post->id]);
        $comment3 = factory(Comment::class)->create(['commentable_type' => 'Post', 'commentable_id' => $post->id]);

        //Call URL
        $response  = $this->call('GET', '/comments', ['type' => 'Post', 'id' => $post->id]);

        //Save response in Json
        $comments = json_decode($response->getContent());

        //Request status 200
        $this->assertEquals(200, $response->getStatusCode());

        //Count comments
        $this->assertEquals(3, count($comments));
    }
}
